/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoalgoritmosjava;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gollo
 */
public class BuscarNombre extends javax.swing.JInternalFrame {

    private GeneroList drama;
    private GeneroList comedy;
    private GeneroList action;
    private GeneroList fiction;
    private GeneroList romance;
    private GeneroList childish;
    
    /**
     * Creates new form BuscarNombre
     */
    public BuscarNombre() {
        super("Buscar Pelicula");
        try {
            Archivo archivo=new Archivo();
            this.drama=archivo.cargarArchivo("1000");
            this.comedy=archivo.cargarArchivo("2000");
            this.action=archivo.cargarArchivo("4000");
            this.romance=archivo.cargarArchivo("5000");
            this.fiction=archivo.cargarArchivo("6000");
            this.childish=archivo.cargarArchivo("3000");
            this.setClosable(true);
            initComponents();
        } catch (IOException ex) {
            Logger.getLogger(BuscarNombre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el nombre:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String texto="";
        if(!drama.buscarPelicula(jTextField1.getText()).printList().equals("The list is empty.\n\n")){
            texto+="   Gender Drama\nCodigo\tNombre\n\n"+drama.buscarPelicula(jTextField1.getText()).printList();
        }
        if(!comedy.buscarPelicula(jTextField1.getText()).printList().equals("The list is empty.\n\n")){
            texto+="\n\n   Gender Comedy\nCodigo\tNombre\n\n"+comedy.buscarPelicula(jTextField1.getText()).printList();
        }
        if(!action.buscarPelicula(jTextField1.getText()).printList().equals("The list is empty.\n\n")){
            texto+="\n\n   Gender Action\nCodigo\tNombre\n\n"+action.buscarPelicula(jTextField1.getText()).printList();
        }
        if(!romance.buscarPelicula(jTextField1.getText()).printList().equals("The list is empty.\n\n")){
            texto+="\n\n   Gender Romance\nCodigo\tNombre\n\n"+romance.buscarPelicula(jTextField1.getText()).printList();
        }
        if(!fiction.buscarPelicula(jTextField1.getText()).printList().equals("The list is empty.\n\n")){
            texto+="\n\n   Gender Fiction\nCodigo\tNombre\n\n"+fiction.buscarPelicula(jTextField1.getText()).printList();
        }
        if(!childish.buscarPelicula(jTextField1.getText()).printList().equals("The list is empty.\n\n")){
            texto+="\n\n   Gender Childish\nCodigo\tNombre\n\n"+childish.buscarPelicula(jTextField1.getText()).printList();
        }
        jTextArea1.setText(texto);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
